/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexao.Conecta;
import DAO.DisciplinaDAO;
import Persistencia.Disciplina;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class CadastrarNotas extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarAluno
     */
    public CadastrarNotas() {
        initComponents();
        redimensionarLogo();
        alterarEspacoNome();
        carregarCbTurma();
        carregarCbDisciplina();
        carregarCbMatriculaAluno();
        setTitle("Boletim Digital");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icones/logo02-blue-24.png")));
    }

    public void redimensionarLogo() {
        String caminhoRelativoIconeLogo = "/Icones/logo02.png";
        String caminhoExecucaoIconeLogo = getClass().getProtectionDomain().getCodeSource().getLocation().getPath();
        String caminhoAbsolutoIconeLogo = caminhoExecucaoIconeLogo + caminhoRelativoIconeLogo;
        ImageIcon icone_logo = new ImageIcon(caminhoAbsolutoIconeLogo);
        Image imagemIconeLogo = icone_logo.getImage();
        Image alterarEscalaIconeLogo = imagemIconeLogo.getScaledInstance(iconeLogo.getWidth(), iconeLogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iconeRedimensionado = new ImageIcon(alterarEscalaIconeLogo);
        iconeLogo.setIcon(iconeRedimensionado);
    }

    public void alterarEspacoNome() {
        String nome = "FIVEBITS";
        nome = nome.replaceAll("(.)", "$0");
        jLabel1.setName(nome);
    }

    private void carregarCbTurma() {
        cbTurma.removeAllItems();
        Connection con = Conecta.iniciaConexao();
        PreparedStatement prepara = null;
        ResultSet rs = null;
        try {
            prepara = con.prepareStatement("SELECT * FROM curso");
            rs = prepara.executeQuery();
            while (rs.next()) {
                cbTurma.addItem(rs.getString("turmaCurso"));
            }
            cbTurma.setSelectedIndex(-1);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao preencher turmas!");
        } finally {
            Conecta.fechaConexao(con, prepara, rs);
        }
    }

    private void carregarCbDisciplina() {
        cbDisciplina.removeAllItems();
        Connection con = Conecta.iniciaConexao();
        PreparedStatement prepara = null;
        ResultSet rs = null;
        try {
            prepara = con.prepareStatement("SELECT * FROM disciplina");
            rs = prepara.executeQuery();
            //rs.first();
            while (rs.next()) {
                cbDisciplina.addItem(rs.getString("codigoDisciplina"));
            }
            cbDisciplina.setSelectedIndex(-1);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao preencher as disciplinas!");
        } finally {
            Conecta.fechaConexao(con, prepara, rs);
        }
    }

    private void carregarCbMatriculaAluno() {

        cbMatriculaAluno.removeAllItems();
        Connection con = Conecta.iniciaConexao();
        PreparedStatement prepara = null;
        ResultSet rs = null;
        try {
            prepara = con.prepareStatement("SELECT * FROM aluno");
            rs = prepara.executeQuery();
            //rs.first();
            while (rs.next()) {
                cbMatriculaAluno.addItem(rs.getString("matriculaAluno"));
            }
            cbMatriculaAluno.setSelectedIndex(-1);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao preencher as matriculas!");
        } finally {
            Conecta.fechaConexao(con, prepara, rs);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        labelNomeUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bLogOff = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tCargaHoraria = new javax.swing.JFormattedTextField();
        tNota1 = new javax.swing.JFormattedTextField();
        tNota2 = new javax.swing.JFormattedTextField();
        tEtapa = new javax.swing.JFormattedTextField();
        tNumeroFaltas = new javax.swing.JFormattedTextField();
        cbTurma = new javax.swing.JComboBox<>();
        cbMatriculaAluno = new javax.swing.JComboBox<>();
        cbDisciplina = new javax.swing.JComboBox<>();
        bSalvar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iconeLogo = new javax.swing.JLabel();
        bSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Alunos");
        setBackground(new java.awt.Color(225, 241, 255));
        setIconImages(null);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(21, 111, 215));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNomeUsuario.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        labelNomeUsuario.setForeground(new java.awt.Color(245, 245, 245));
        labelNomeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomeUsuario.setText("Professor");
        jPanel3.add(labelNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 20));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 245, 245));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bem-Vindo!");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        bLogOff.setBackground(new java.awt.Color(21, 111, 215));
        bLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/logout-24 - white.png"))); // NOI18N
        bLogOff.setBorderPainted(false);
        bLogOff.setContentAreaFilled(false);
        bLogOff.setFocusPainted(false);
        bLogOff.setFocusable(false);
        bLogOff.setRequestFocusEnabled(false);
        bLogOff.setRolloverEnabled(false);
        bLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogOffActionPerformed(evt);
            }
        });
        jPanel3.add(bLogOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 30, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 540));

        jPanel2.setBackground(new java.awt.Color(225, 241, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(122, 122, 122));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Disciplina:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(122, 122, 122));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Turma:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 122, 122));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("2º Nota:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(122, 122, 122));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Carga Horária:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(122, 122, 122));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Faltas:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(122, 122, 122));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Etapa:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(122, 122, 122));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("1º Nota:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(122, 122, 122));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Matricula:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        tCargaHoraria.setBackground(new java.awt.Color(225, 241, 255));
        tCargaHoraria.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(158, 158, 158)));
        tCargaHoraria.setColumns(10);
        tCargaHoraria.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tCargaHoraria.setSelectedTextColor(new java.awt.Color(225, 241, 255));
        tCargaHoraria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCargaHorariaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCargaHorariaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCargaHorariaKeyTyped(evt);
            }
        });
        jPanel2.add(tCargaHoraria, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 60, -1));

        tNota1.setBackground(new java.awt.Color(225, 241, 255));
        tNota1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(158, 158, 158)));
        tNota1.setColumns(10);
        tNota1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tNota1.setSelectedTextColor(new java.awt.Color(225, 241, 255));
        tNota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNota1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tNota1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNota1KeyTyped(evt);
            }
        });
        jPanel2.add(tNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 60, -1));

        tNota2.setBackground(new java.awt.Color(225, 241, 255));
        tNota2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(158, 158, 158)));
        tNota2.setColumns(10);
        tNota2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tNota2.setSelectedTextColor(new java.awt.Color(225, 241, 255));
        tNota2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNota2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tNota2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNota2KeyTyped(evt);
            }
        });
        jPanel2.add(tNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 60, -1));

        tEtapa.setBackground(new java.awt.Color(225, 241, 255));
        tEtapa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(158, 158, 158)));
        tEtapa.setColumns(10);
        tEtapa.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tEtapa.setSelectedTextColor(new java.awt.Color(225, 241, 255));
        tEtapa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tEtapaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tEtapaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tEtapaKeyTyped(evt);
            }
        });
        jPanel2.add(tEtapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 60, -1));

        tNumeroFaltas.setBackground(new java.awt.Color(225, 241, 255));
        tNumeroFaltas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(158, 158, 158)));
        tNumeroFaltas.setColumns(10);
        tNumeroFaltas.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tNumeroFaltas.setSelectedTextColor(new java.awt.Color(225, 241, 255));
        tNumeroFaltas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNumeroFaltasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tNumeroFaltasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNumeroFaltasKeyTyped(evt);
            }
        });
        jPanel2.add(tNumeroFaltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 60, -1));

        cbTurma.setBackground(new java.awt.Color(225, 241, 255));
        cbTurma.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        cbTurma.setForeground(new java.awt.Color(122, 122, 122));
        cbTurma.setMaximumRowCount(2);
        cbTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbTurmaMouseEntered(evt);
            }
        });
        jPanel2.add(cbTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 70, -1));

        cbMatriculaAluno.setBackground(new java.awt.Color(225, 241, 255));
        cbMatriculaAluno.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        cbMatriculaAluno.setForeground(new java.awt.Color(122, 122, 122));
        cbMatriculaAluno.setMaximumRowCount(2);
        cbMatriculaAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbMatriculaAlunoMouseEntered(evt);
            }
        });
        jPanel2.add(cbMatriculaAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 120, -1));

        cbDisciplina.setBackground(new java.awt.Color(225, 241, 255));
        cbDisciplina.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        cbDisciplina.setForeground(new java.awt.Color(122, 122, 122));
        cbDisciplina.setMaximumRowCount(2);
        cbDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbDisciplinaMouseEntered(evt);
            }
        });
        jPanel2.add(cbDisciplina, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 120, -1));

        bSalvar.setBackground(new java.awt.Color(41, 131, 235));
        bSalvar.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        bSalvar.setForeground(new java.awt.Color(245, 245, 245));
        bSalvar.setText("Salvar dados");
        bSalvar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(225, 241, 255)));
        bSalvar.setBorderPainted(false);
        bSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSalvarMouseEntered(evt);
            }
        });
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(bSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 230, 50));

        jLabel12.setBackground(new java.awt.Color(122, 122, 122));
        jLabel12.setFont(new java.awt.Font("Roboto Light", 0, 27)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(122, 122, 122));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Registro de Notas");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 800, 540));

        jPanel1.setBackground(new java.awt.Color(41, 131, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("FIVEBITS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        jPanel1.add(iconeLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 50));

        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/multiply-19-white.png"))); // NOI18N
        bSair.setContentAreaFilled(false);
        bSair.setFocusPainted(false);
        bSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSairMouseExited(evt);
            }
        });
        jPanel1.add(bSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    static int xx, yy;

    private void bSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bSairMouseClicked

    private void bSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseEntered
        // TODO add your handling code here:
        bSair.setOpaque(true);
        bSair.setBackground(new Color(255, 96, 92));
        bSair.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_bSairMouseEntered

    private void bSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseExited
        // TODO add your handling code here:
        bSair.setOpaque(false);
    }//GEN-LAST:event_bSairMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_formMouseDragged

    private void bLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogOffActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement prepara = null;
        ResultSet rs = null;
        Conecta.fechaConexao(con, prepara, rs);
        //con.close();
        int logOff = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja fazer logout?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (logOff == JOptionPane.YES_OPTION) {
            Conecta.fechaConexao(con, prepara, rs);
            new Login().setVisible(true);
            this.dispose();
            Conecta.fechaConexao(con, prepara, rs);
        } else {
            int Octa = 1 + 1;
        }
    }//GEN-LAST:event_bLogOffActionPerformed

    private void tCargaHorariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCargaHorariaKeyPressed
        // TODO add your handling code here:
        String numerosInseridosMatricula = tCargaHoraria.getText();
        int quantiaNumerosMatricula = numerosInseridosMatricula.length();
        if (quantiaNumerosMatricula > 3) {
            numerosInseridosMatricula = numerosInseridosMatricula.substring(0, numerosInseridosMatricula.length() - 1);
            tCargaHoraria.setText(numerosInseridosMatricula);
        }
    }//GEN-LAST:event_tCargaHorariaKeyPressed

    private void tCargaHorariaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCargaHorariaKeyReleased
        // TODO add your handling code here:
        String numerosInseridosMatricula = tCargaHoraria.getText();
        int quantiaNumerosMatricula = numerosInseridosMatricula.length();
        if (quantiaNumerosMatricula > 3) {
            numerosInseridosMatricula = numerosInseridosMatricula.substring(0, numerosInseridosMatricula.length() - 1);
            tCargaHoraria.setText(numerosInseridosMatricula);
        }
    }//GEN-LAST:event_tCargaHorariaKeyReleased

    private void tCargaHorariaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCargaHorariaKeyTyped
        // TODO add your handling code here:
        String teclasAceitasMatricula = "0123456789";
        if (!teclasAceitasMatricula.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tCargaHorariaKeyTyped

    private void tNota1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNota1KeyPressed
        // TODO add your handling code here:
        String numerosInserisoNota = tNota1.getText();
        int quantiaNumerosNota = numerosInserisoNota.length();
        if (quantiaNumerosNota > 4) {
            numerosInserisoNota = numerosInserisoNota.substring(0, numerosInserisoNota.length() - 1);
            tNota1.setText(numerosInserisoNota);
        }
    }//GEN-LAST:event_tNota1KeyPressed

    private void tNota1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNota1KeyReleased
        // TODO add your handling code here:
        String numerosInserisoNota = tNota1.getText();
        int quantiaNumerosNota = numerosInserisoNota.length();
        if (quantiaNumerosNota > 4) {
            numerosInserisoNota = numerosInserisoNota.substring(0, numerosInserisoNota.length() - 1);
            tNota1.setText(numerosInserisoNota);
        }
    }//GEN-LAST:event_tNota1KeyReleased

    private void tNota1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNota1KeyTyped
        // TODO add your handling code here:
        String teclasAceitas = "0123456789.";
        if (!teclasAceitas.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tNota1KeyTyped

    private void tNota2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNota2KeyPressed
        // TODO add your handling code here:
        String numerosInserisoNota = tNota2.getText();
        int quantiaNumerosNota = numerosInserisoNota.length();
        if (quantiaNumerosNota > 4) {
            numerosInserisoNota = numerosInserisoNota.substring(0, numerosInserisoNota.length() - 1);
            tNota2.setText(numerosInserisoNota);
        }
    }//GEN-LAST:event_tNota2KeyPressed

    private void tNota2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNota2KeyReleased
        // TODO add your handling code here:
        String numerosInserisoNota = tNota2.getText();
        int quantiaNumerosNota = numerosInserisoNota.length();
        if (quantiaNumerosNota > 4) {
            numerosInserisoNota = numerosInserisoNota.substring(0, numerosInserisoNota.length() - 1);
            tNota2.setText(numerosInserisoNota);
        }
    }//GEN-LAST:event_tNota2KeyReleased

    private void tNota2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNota2KeyTyped
        // TODO add your handling code here:
        String teclasAceitas = "0123456789.";
        if (!teclasAceitas.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tNota2KeyTyped

    private void tEtapaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tEtapaKeyPressed
        // TODO add your handling code here:
        String caracteres = tEtapa.getText();
        int quantia = caracteres.length();
        if (quantia > 1) {
            caracteres = caracteres.substring(0, caracteres.length() - 1);
            tEtapa.setText(caracteres);
        }
    }//GEN-LAST:event_tEtapaKeyPressed

    private void tEtapaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tEtapaKeyReleased
        // TODO add your handling code here:
        String caracteres = tEtapa.getText();
        int quantia = caracteres.length();
        if (quantia > 1) {
            caracteres = caracteres.substring(0, caracteres.length() - 1);
            tEtapa.setText(caracteres);
        }
    }//GEN-LAST:event_tEtapaKeyReleased

    private void tEtapaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tEtapaKeyTyped
        // TODO add your handling code here:
        String teclasAceitas = "1234";
        if (!teclasAceitas.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tEtapaKeyTyped

    private void tNumeroFaltasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNumeroFaltasKeyPressed
        // TODO add your handling code here:
        String caracteres = tNumeroFaltas.getText();
        int quantia = caracteres.length();
        if (quantia > 3) {
            caracteres = caracteres.substring(0, caracteres.length() - 1);
            tNumeroFaltas.setText(caracteres);
        }
    }//GEN-LAST:event_tNumeroFaltasKeyPressed

    private void tNumeroFaltasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNumeroFaltasKeyReleased
        // TODO add your handling code here:
        String caracteres = tNumeroFaltas.getText();
        int quantia = caracteres.length();
        if (quantia > 3) {
            caracteres = caracteres.substring(0, caracteres.length() - 1);
            tNumeroFaltas.setText(caracteres);
        }
    }//GEN-LAST:event_tNumeroFaltasKeyReleased

    private void tNumeroFaltasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNumeroFaltasKeyTyped
        // TODO add your handling code here:
        String teclasAceitas = "0123456789";
        if (!teclasAceitas.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tNumeroFaltasKeyTyped

    private void bSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalvarMouseEntered
        // TODO add your handling code here:
        bSalvar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_bSalvarMouseEntered

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        // TODO add your handling code here:
        double operacaoMedia, x, y;
        int z;
        String a, b;
        Disciplina d = new Disciplina();
        DisciplinaDAO dDAO = new DisciplinaDAO();
        a = tNota1.getText();
        b = tNota2.getText();
        a = a.replace(',', '.');
        x = Double.parseDouble(a);
        b = b.replace(',', '.');
        y = Double.parseDouble(b);
        if (tEtapa.getText().equals("")) {
            z = 1;
        } else {
            z = Integer.parseInt(tEtapa.getText());
        }
        operacaoMedia = (x + y) / 2;
        Object codigoMatriculaObjeto = cbMatriculaAluno.getSelectedItem();
        int codigoMAluno = Integer.parseInt((String) codigoMatriculaObjeto);
        Object codigoDisciplinaObjeto = cbDisciplina.getSelectedItem();
        int codigoD = Integer.parseInt((String) codigoDisciplinaObjeto);
        d.setCodigoDisciplina(codigoD);
        d.setMatriculaAluno(codigoMAluno);
        d.setCargaHoraria(Integer.parseInt(tCargaHoraria.getText()));
        d.setPrimeiraNota(x);
        d.setSegundaNota(y);
        d.setMedia(operacaoMedia);
        d.setEtapa(z);
        d.setNumeroFaltas(Integer.parseInt(tNumeroFaltas.getText()));
        dDAO.cadastrarNotas(d);
    }//GEN-LAST:event_bSalvarActionPerformed

    private void cbMatriculaAlunoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMatriculaAlunoMouseEntered
        // TODO add your handling code here:
        cbMatriculaAluno.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cbMatriculaAlunoMouseEntered

    private void cbDisciplinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDisciplinaMouseEntered
        // TODO add your handling code here:
        cbDisciplina.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cbDisciplinaMouseEntered

    private void cbTurmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTurmaMouseEntered
        // TODO add your handling code here:
        cbTurma.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cbTurmaMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogOff;
    private javax.swing.JButton bSair;
    private javax.swing.JButton bSalvar;
    private javax.swing.JComboBox<String> cbDisciplina;
    private javax.swing.JComboBox<String> cbMatriculaAluno;
    private javax.swing.JComboBox<String> cbTurma;
    private javax.swing.JLabel iconeLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelNomeUsuario;
    private javax.swing.JFormattedTextField tCargaHoraria;
    private javax.swing.JFormattedTextField tEtapa;
    private javax.swing.JFormattedTextField tNota1;
    private javax.swing.JFormattedTextField tNota2;
    private javax.swing.JFormattedTextField tNumeroFaltas;
    // End of variables declaration//GEN-END:variables
}
