/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexao.Conecta;
import DAO.AlunoDAO;
import Jm.JMascara;
import Persistencia.Aluno;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author rodri
 */
public class CadastrarAluno extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarAluno
     */
    public CadastrarAluno() {
        initComponents();
        redimensionarLogo();
        alterarEspacoNome();
        carregarCbTurma();
        setTitle("Boletim Digital");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icones/logo02-blue-24.png")));
    }

    public void redimensionarLogo() {
        String caminhoRelativoIconeLogo = "/Icones/logo02.png";
        String caminhoExecucaoIconeLogo = getClass().getProtectionDomain().getCodeSource().getLocation().getPath();
        String caminhoAbsolutoIconeLogo = caminhoExecucaoIconeLogo + caminhoRelativoIconeLogo;
        ImageIcon icone_logo = new ImageIcon(caminhoAbsolutoIconeLogo);
        Image imagemIconeLogo = icone_logo.getImage();
        Image alterarEscalaIconeLogo = imagemIconeLogo.getScaledInstance(iconeLogo.getWidth(), iconeLogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iconeRedimensionado = new ImageIcon(alterarEscalaIconeLogo);
        iconeLogo.setIcon(iconeRedimensionado);
    }

    public void alterarEspacoNome() {
        String nome = "FIVEBITS";
        nome = nome.replaceAll("(.)", "$0");

        jLabel1.setText(nome);
    }

    private void carregarCbTurma() {
        cbTurmaAluno.removeAllItems();
        Connection con = Conecta.iniciaConexao();
        PreparedStatement prepara = null;
        ResultSet rs = null;
        try {
            prepara = con.prepareStatement("SELECT * FROM curso");
            rs = prepara.executeQuery();
            while (rs.next()) {
                cbTurmaAluno.addItem(rs.getString("turmaCurso"));
            }
            cbTurmaAluno.setSelectedIndex(-1);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao preencher turmas!");
        } finally {
            Conecta.fechaConexao(con, prepara, rs);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bLogOff = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tMatriculaAluno = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tCpfAluno = new javax.swing.JFormattedTextField();
        tSenhaAluno = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        tEmailAluno = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        tNomeAluno = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelMostrarSenha = new javax.swing.JLabel();
        labelOcultarSenha = new javax.swing.JLabel();
        cbTurnoAluno = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbTurmaAluno = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bCadastrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iconeLogo = new javax.swing.JLabel();
        bSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Alunos");
        setBackground(new java.awt.Color(225, 241, 255));
        setIconImages(null);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(21, 111, 215));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 245, 245));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Administrador");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 245, 245));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bem-Vindo!");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        bLogOff.setBackground(new java.awt.Color(21, 111, 215));
        bLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/logout-24 - white.png"))); // NOI18N
        bLogOff.setBorderPainted(false);
        bLogOff.setContentAreaFilled(false);
        bLogOff.setFocusPainted(false);
        bLogOff.setFocusable(false);
        bLogOff.setRequestFocusEnabled(false);
        bLogOff.setRolloverEnabled(false);
        bLogOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bLogOffMouseEntered(evt);
            }
        });
        bLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogOffActionPerformed(evt);
            }
        });
        jPanel3.add(bLogOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 30, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 560));

        jPanel2.setBackground(new java.awt.Color(225, 241, 255));

        tMatriculaAluno.setBackground(new java.awt.Color(225, 241, 255));
        tMatriculaAluno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(158, 158, 158)));
        tMatriculaAluno.setColumns(10);
        tMatriculaAluno.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tMatriculaAluno.setSelectedTextColor(new java.awt.Color(225, 241, 255));
        tMatriculaAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tMatriculaAlunoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tMatriculaAlunoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tMatriculaAlunoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 122, 122));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Matricula:");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(122, 122, 122));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CPF:");

        tCpfAluno.setBackground(new java.awt.Color(225, 241, 255));
        tCpfAluno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(158, 158, 158)));
        tCpfAluno.setColumns(10);
        tCpfAluno.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tCpfAluno.setSelectedTextColor(new java.awt.Color(225, 241, 255));
        tCpfAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCpfAlunoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCpfAlunoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCpfAlunoKeyTyped(evt);
            }
        });

        tSenhaAluno.setBackground(new java.awt.Color(225, 241, 255));
        tSenhaAluno.setColumns(32);
        tSenhaAluno.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        tSenhaAluno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(158, 158, 158)));
        tSenhaAluno.setSelectedTextColor(new java.awt.Color(225, 241, 255));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(122, 122, 122));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Senha:");

        tEmailAluno.setBackground(new java.awt.Color(225, 241, 255));
        tEmailAluno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(158, 158, 158)));
        tEmailAluno.setColumns(10);
        tEmailAluno.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tEmailAluno.setSelectedTextColor(new java.awt.Color(225, 241, 255));
        tEmailAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tEmailAlunoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tEmailAlunoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tEmailAlunoKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(122, 122, 122));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("E-mail:");

        tNomeAluno.setBackground(new java.awt.Color(225, 241, 255));
        tNomeAluno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(158, 158, 158)));
        tNomeAluno.setColumns(10);
        tNomeAluno.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tNomeAluno.setSelectedTextColor(new java.awt.Color(225, 241, 255));
        tNomeAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNomeAlunoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tNomeAlunoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNomeAlunoKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(122, 122, 122));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nome:");

        jPanel4.setBackground(new java.awt.Color(225, 241, 255));
        jPanel4.setLayout(null);

        labelMostrarSenha.setFont(new java.awt.Font("Roboto Medium", 0, 28)); // NOI18N
        labelMostrarSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMostrarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/eye-19.png"))); // NOI18N
        labelMostrarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMostrarSenhaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelMostrarSenhaMousePressed(evt);
            }
        });
        jPanel4.add(labelMostrarSenha);
        labelMostrarSenha.setBounds(0, -1, 20, 20);

        labelOcultarSenha.setFont(new java.awt.Font("Roboto Medium", 0, 28)); // NOI18N
        labelOcultarSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOcultarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/hide-19.png"))); // NOI18N
        labelOcultarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelOcultarSenhaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelOcultarSenhaMousePressed(evt);
            }
        });
        jPanel4.add(labelOcultarSenha);
        labelOcultarSenha.setBounds(0, 0, 19, 19);

        cbTurnoAluno.setBackground(new java.awt.Color(225, 241, 255));
        cbTurnoAluno.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        cbTurnoAluno.setForeground(new java.awt.Color(122, 122, 122));
        cbTurnoAluno.setMaximumRowCount(3);
        cbTurnoAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));
        cbTurnoAluno.setSelectedIndex(-1);
        cbTurnoAluno.setToolTipText("Selectione a turma");
        cbTurnoAluno.setBorder(null);
        cbTurnoAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbTurnoAluno.setOpaque(false);
        cbTurnoAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbTurnoAlunoMouseEntered(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(122, 122, 122));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Turno:");

        cbTurmaAluno.setBackground(new java.awt.Color(225, 241, 255));
        cbTurmaAluno.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        cbTurmaAluno.setForeground(new java.awt.Color(122, 122, 122));
        cbTurmaAluno.setMaximumRowCount(3);
        cbTurmaAluno.setToolTipText("Selectione a turma");
        cbTurmaAluno.setBorder(null);
        cbTurmaAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbTurmaAluno.setOpaque(false);
        cbTurmaAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbTurmaAlunoMouseEntered(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(122, 122, 122));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Turma:");

        jLabel11.setBackground(new java.awt.Color(122, 122, 122));
        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 27)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(122, 122, 122));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cadastro de Alunos");

        bCadastrar.setBackground(new java.awt.Color(41, 131, 235));
        bCadastrar.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        bCadastrar.setForeground(new java.awt.Color(245, 245, 245));
        bCadastrar.setText("Cadastrar");
        bCadastrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(225, 241, 255)));
        bCadastrar.setBorderPainted(false);
        bCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCadastrarMouseEntered(evt);
            }
        });
        bCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tEmailAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(tNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(tMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel4))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(147, 147, 147)
                                                .addComponent(jLabel8))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(36, 36, 36)
                                                        .addComponent(tCpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(24, 24, 24)
                                                        .addComponent(jLabel5)))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(4, 4, 4)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel6)
                                                            .addComponent(jLabel9))
                                                        .addGap(39, 39, 39)
                                                        .addComponent(cbTurnoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(tSenhaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addGap(27, 27, 27)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cbTurmaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(278, 278, 278))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTurnoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTurmaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tEmailAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tSenhaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)))
                .addComponent(bCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 800, 560));

        jPanel1.setBackground(new java.awt.Color(41, 131, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("FIVEBITS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        jPanel1.add(iconeLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 50));

        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/multiply-19-white.png"))); // NOI18N
        bSair.setContentAreaFilled(false);
        bSair.setFocusPainted(false);
        bSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSairMouseExited(evt);
            }
        });
        jPanel1.add(bSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    static int xx, yy;
    int Octa;
    Border bordaCliqueTexto = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.decode("#2983EB"));
    Border bordaCliqueTextoFora = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("#9E9E9E"));


    private void bSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bSairMouseClicked

    private void bSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseEntered
        // TODO add your handling code here:
        bSair.setOpaque(true);
        bSair.setBackground(new Color(255, 96, 92));
        bSair.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_bSairMouseEntered

    private void bSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseExited
        // TODO add your handling code here:
        bSair.setOpaque(false);
    }//GEN-LAST:event_bSairMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_formMouseDragged

    private void bLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogOffActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement prepara = null;
        ResultSet rs = null;
        Conecta.fechaConexao(con, prepara, rs);
        int logOff = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja fazer logout?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (logOff == JOptionPane.YES_OPTION) {
            Conecta.fechaConexao(con, prepara, rs);
            new Login().setVisible(true);
            this.dispose();
            Conecta.fechaConexao(con, prepara, rs);
        } else {
            Octa = Octa + 1;
        }
    }//GEN-LAST:event_bLogOffActionPerformed

    private void tMatriculaAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tMatriculaAlunoKeyReleased
        // TODO add your handling code here:
        String numerosInseridosMatricula = tMatriculaAluno.getText();
        int quantiaNumerosMatricula = numerosInseridosMatricula.length();
        if (quantiaNumerosMatricula > 10) {
            numerosInseridosMatricula = numerosInseridosMatricula.substring(0, numerosInseridosMatricula.length() - 1);
            tMatriculaAluno.setText(numerosInseridosMatricula);
        }
    }//GEN-LAST:event_tMatriculaAlunoKeyReleased

    private void tMatriculaAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tMatriculaAlunoKeyPressed
        // TODO add your handling code here:
        String numerosInseridosMatricula = tMatriculaAluno.getText();
        int quantiaNumerosMatricula = numerosInseridosMatricula.length();
        if (quantiaNumerosMatricula > 10) {
            numerosInseridosMatricula = numerosInseridosMatricula.substring(0, numerosInseridosMatricula.length() - 1);
            tMatriculaAluno.setText(numerosInseridosMatricula);
        }
    }//GEN-LAST:event_tMatriculaAlunoKeyPressed

    private void tMatriculaAlunoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tMatriculaAlunoKeyTyped
        // TODO add your handling code here:
        String teclasAceitasMatricula = "0123456789";
        if (!teclasAceitasMatricula.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tMatriculaAlunoKeyTyped

    private void tCpfAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCpfAlunoKeyPressed
        // TODO add your handling code here author rodrigo:
        String numerosInseridosCpf = tCpfAluno.getText();
        int quantiaNumerosCpf = numerosInseridosCpf.length();
        if (quantiaNumerosCpf > 14) {
            numerosInseridosCpf = numerosInseridosCpf.substring(0, numerosInseridosCpf.length() - 1);
            tCpfAluno.setText(numerosInseridosCpf);
        }
    }//GEN-LAST:event_tCpfAlunoKeyPressed

    private void tCpfAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCpfAlunoKeyReleased
        // TODO add your handling code here:
        String numerosInseridosCpf = tCpfAluno.getText();
        int quantiaNumerosCpf = numerosInseridosCpf.length();
        if (quantiaNumerosCpf > 14) {
            numerosInseridosCpf = numerosInseridosCpf.substring(0, numerosInseridosCpf.length() - 1);
            tCpfAluno.setText(numerosInseridosCpf);
        }
    }//GEN-LAST:event_tCpfAlunoKeyReleased

    private void tCpfAlunoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCpfAlunoKeyTyped
        // TODO add your handling code here:
        tCpfAluno.setText(JMascara.GetJmascaraCpfCnpj(tCpfAluno.getText()));
        String teclasAceitasCpf = ".-0123456789";
        if (!teclasAceitasCpf.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tCpfAlunoKeyTyped

    private void tEmailAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tEmailAlunoKeyPressed
        // TODO add your handling code here:
        String caracteresInseridosEmail = tEmailAluno.getText();
        int quantiaCaracteresEmail = caracteresInseridosEmail.length();
        if (quantiaCaracteresEmail > 30) {
            caracteresInseridosEmail = caracteresInseridosEmail.substring(0, caracteresInseridosEmail.length() - 1);
            tEmailAluno.setText(caracteresInseridosEmail);
        }
    }//GEN-LAST:event_tEmailAlunoKeyPressed

    private void tEmailAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tEmailAlunoKeyReleased
        // TODO add your handling code here:
        String caracteresInseridosEmail = tEmailAluno.getText();
        int quantiaCaracteresEmail = caracteresInseridosEmail.length();
        if (quantiaCaracteresEmail > 30) {
            caracteresInseridosEmail = caracteresInseridosEmail.substring(0, caracteresInseridosEmail.length() - 1);
            tEmailAluno.setText(caracteresInseridosEmail);
        }
    }//GEN-LAST:event_tEmailAlunoKeyReleased

    private void tEmailAlunoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tEmailAlunoKeyTyped
        // TODO add your handling code here:
        String teclasAceitasEmail = "0123456789abcdefghijklmnopqrstuvwxyzçABCDEFGHIJKLMNOPQRSTUVWXYZÇ._@-´~^`";
        if (!teclasAceitasEmail.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tEmailAlunoKeyTyped

    private void tNomeAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNomeAlunoKeyPressed
        // TODO add your handling code here:
        String caracteresInseridosNome = tNomeAluno.getText();
        int quantiaCaracteresNome = caracteresInseridosNome.length();
        if (quantiaCaracteresNome > 60) {
            caracteresInseridosNome = caracteresInseridosNome.substring(0, caracteresInseridosNome.length() - 1);
            tNomeAluno.setText(caracteresInseridosNome);
        }
    }//GEN-LAST:event_tNomeAlunoKeyPressed

    private void tNomeAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNomeAlunoKeyReleased
        // TODO add your handling code here:
        String caracteresInseridosNome = tNomeAluno.getText();
        int quantiaCaracteresNome = caracteresInseridosNome.length();
        if (quantiaCaracteresNome > 60) {
            caracteresInseridosNome = caracteresInseridosNome.substring(0, caracteresInseridosNome.length() - 1);
            tNomeAluno.setText(caracteresInseridosNome);
        }
    }//GEN-LAST:event_tNomeAlunoKeyReleased

    private void tNomeAlunoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNomeAlunoKeyTyped
        // TODO add your handling code here:
        String teclasAceitasNome = "abcdefghijklmnopqrstuvwxyzçABCDEFGHIJKLMNOPQRSTUVWXYZÇ ´~^`";
        if (!teclasAceitasNome.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tNomeAlunoKeyTyped

    private void bLogOffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogOffMouseEntered
        // TODO add your handling code here:
        bLogOff.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_bLogOffMouseEntered

    private void labelMostrarSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMostrarSenhaMouseEntered
        // TODO add your handling code here:
        labelMostrarSenha.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labelMostrarSenhaMouseEntered

    private void labelMostrarSenhaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMostrarSenhaMousePressed
        // TODO add your handling code here:
        labelMostrarSenha.setVisible(false);
        labelOcultarSenha.setVisible(true);
        tSenhaAluno.setEchoChar((char) 0);
        tSenhaAluno.setFont(new java.awt.Font("Roboto Light", 0, 15));
    }//GEN-LAST:event_labelMostrarSenhaMousePressed

    private void labelOcultarSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOcultarSenhaMouseEntered
        // TODO add your handling code here:
        labelOcultarSenha.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labelOcultarSenhaMouseEntered

    private void labelOcultarSenhaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOcultarSenhaMousePressed
        // TODO add your handling code here:
        labelOcultarSenha.setVisible(false);
        labelMostrarSenha.setVisible(true);
        tSenhaAluno.setEchoChar('*');
        tSenhaAluno.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_labelOcultarSenhaMousePressed

    private void bCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarActionPerformed
        // TODO add your handling code here:
        Aluno a = new Aluno();
        AlunoDAO aDAO = new AlunoDAO();
        Object codigoTurmaObjeto = cbTurmaAluno.getSelectedItem();
        int codigoTAluno = Integer.parseInt((String) codigoTurmaObjeto);
        Object nomeTurnoObjeto = cbTurnoAluno.getSelectedItem();
        String nomeTurno = (String) nomeTurnoObjeto;
        String cpfMascaraAluno = JMascara.GetJmascaraLimpar(tCpfAluno.getText());
        char[] converteSenhaAluno = tSenhaAluno.getPassword();
        String stringSenhaAluno = new String(converteSenhaAluno);
        a.setMatriculaAluno(Integer.parseInt(tMatriculaAluno.getText()));
        a.setCpfAluno(cpfMascaraAluno);
        a.setNomeAluno(tNomeAluno.getText());
        a.setTurnoAluno(nomeTurno);
        a.setTurmaAluno(codigoTAluno);
        a.setSenhaAluno(stringSenhaAluno);
        a.setEmailAluno(tEmailAluno.getText());
        aDAO.cadastrarAluno(a);
    }//GEN-LAST:event_bCadastrarActionPerformed

    private void bCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadastrarMouseEntered
        // TODO add your handling code here:
        bCadastrar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_bCadastrarMouseEntered

    private void cbTurmaAlunoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTurmaAlunoMouseEntered
        // TODO add your handling code here:
        cbTurmaAluno.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cbTurmaAlunoMouseEntered

    private void cbTurnoAlunoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTurnoAlunoMouseEntered
        // TODO add your handling code here:
        cbTurmaAluno.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cbTurnoAlunoMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadastrar;
    private javax.swing.JButton bLogOff;
    private javax.swing.JButton bSair;
    private javax.swing.JComboBox<String> cbTurmaAluno;
    private javax.swing.JComboBox<String> cbTurnoAluno;
    private javax.swing.JLabel iconeLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelMostrarSenha;
    private javax.swing.JLabel labelOcultarSenha;
    private javax.swing.JFormattedTextField tCpfAluno;
    private javax.swing.JFormattedTextField tEmailAluno;
    private javax.swing.JFormattedTextField tMatriculaAluno;
    private javax.swing.JFormattedTextField tNomeAluno;
    private javax.swing.JPasswordField tSenhaAluno;
    // End of variables declaration//GEN-END:variables
}
