/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.AdministradorDAO;
import DAO.professorDAO;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import Jm.JMascara;
import Persistencia.Professor;
import Persistencia.Admin;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author rodri
 */
public class Login extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        lErroLogin.setVisible(false);
        labelOcultarSenha.setVisible(false);
        bLogin.setEnabled(true);
        redimensionarLogo();
        setTitle("Boletim Digital");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icones/logo02-blue-24.png")));
    }

    public void redimensionarLogo() {
        String caminhoRelativoIconeLogo = "/Icones/logo02-blue.png";
        String caminhoExecucaoIconeLogo = getClass().getProtectionDomain().getCodeSource().getLocation().getPath();
        String caminhoAbsolutoIconeLogo = caminhoExecucaoIconeLogo + caminhoRelativoIconeLogo;
        ImageIcon icone_logo = new ImageIcon(caminhoAbsolutoIconeLogo);
        Image imagemIconeLogo = icone_logo.getImage();
        Image alterarEscalaIconeLogo = imagemIconeLogo.getScaledInstance(iconeLogo.getWidth(), iconeLogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iconeRedimensionado = new ImageIcon(alterarEscalaIconeLogo);
        iconeLogo.setIcon(iconeRedimensionado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLogin = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        tCpf = new javax.swing.JFormattedTextField();
        tSenha = new javax.swing.JPasswordField();
        labelMostrarSenha = new javax.swing.JLabel();
        labelOcultarSenha = new javax.swing.JLabel();
        bLogin = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lErroLogin = new javax.swing.JLabel();
        radialProfessor = new javax.swing.JRadioButton();
        radialAdmin = new javax.swing.JRadioButton();
        iconeLogo = new javax.swing.JLabel();
        bSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boletim Digital");
        setIconImages(null);
        setUndecorated(true);

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(41, 131, 235));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(41, 131, 235));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(306, 370));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        tCpf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(158, 158, 158)));
        tCpf.setColumns(11);
        tCpf.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        tCpf.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tCpf.setSelectionColor(new java.awt.Color(4, 165, 140));
        tCpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tCpfMouseClicked(evt);
            }
        });
        tCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCpfKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCpfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCpfKeyTyped(evt);
            }
        });

        tSenha.setColumns(32);
        tSenha.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        tSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(158, 158, 158)));
        tSenha.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        tSenha.setSelectionColor(new java.awt.Color(4, 165, 140));
        tSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tSenhaMouseClicked(evt);
            }
        });
        tSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tSenhaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tSenhaKeyReleased(evt);
            }
        });

        labelMostrarSenha.setFont(new java.awt.Font("Roboto Medium", 0, 28)); // NOI18N
        labelMostrarSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMostrarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/eye-19.png"))); // NOI18N
        labelMostrarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMostrarSenhaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelMostrarSenhaMousePressed(evt);
            }
        });

        labelOcultarSenha.setFont(new java.awt.Font("Roboto Medium", 0, 28)); // NOI18N
        labelOcultarSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOcultarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/hide-19.png"))); // NOI18N
        labelOcultarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelOcultarSenhaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelOcultarSenhaMousePressed(evt);
            }
        });

        bLogin.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        bLogin.setkAllowGradient(false);
        bLogin.setkBackGroundColor(new java.awt.Color(2, 145, 211));
        bLogin.setkBorderRadius(0);
        bLogin.setkEndColor(new java.awt.Color(2, 145, 211));
        bLogin.setkHoverColor(new java.awt.Color(2, 145, 211));
        bLogin.setkHoverEndColor(new java.awt.Color(2, 145, 211));
        bLogin.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        bLogin.setkHoverStartColor(new java.awt.Color(2, 145, 211));
        bLogin.setkIndicatorColor(new java.awt.Color(2, 145, 211));
        bLogin.setkIndicatorThickness(1);
        bLogin.setkPressedColor(new java.awt.Color(2, 145, 211));
        bLogin.setkSelectedColor(new java.awt.Color(2, 145, 211));
        bLogin.setkStartColor(new java.awt.Color(2, 145, 211));
        bLogin.setLabel("Entrar");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(122, 122, 122));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CPF");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(122, 122, 122));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Senha");

        jLabel4.setBackground(new java.awt.Color(41, 131, 235));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(41, 131, 235));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FIVEBITS");

        lErroLogin.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lErroLogin.setForeground(new java.awt.Color(255, 96, 92));

        radialProfessor.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupLogin.add(radialProfessor);
        radialProfessor.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        radialProfessor.setForeground(new java.awt.Color(122, 122, 122));
        radialProfessor.setText("Professor");
        radialProfessor.setContentAreaFilled(false);
        radialProfessor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radialProfessor.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radialProfessor.setMaximumSize(new java.awt.Dimension(90, 25));
        radialProfessor.setMinimumSize(new java.awt.Dimension(90, 25));
        radialProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radialProfessorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                radialProfessorMouseEntered(evt);
            }
        });

        radialAdmin.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupLogin.add(radialAdmin);
        radialAdmin.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        radialAdmin.setForeground(new java.awt.Color(122, 122, 122));
        radialAdmin.setText("Administrador");
        radialAdmin.setContentAreaFilled(false);
        radialAdmin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radialAdmin.setMaximumSize(new java.awt.Dimension(90, 25));
        radialAdmin.setMinimumSize(new java.awt.Dimension(90, 25));
        radialAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radialAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                radialAdminMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tCpf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radialProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radialAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(tSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelOcultarSenha)
                            .addComponent(labelMostrarSenha))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lErroLogin)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(iconeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelOcultarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMostrarSenha)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radialProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radialAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(lErroLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/multiply-19-white.png"))); // NOI18N
        bSair.setContentAreaFilled(false);
        bSair.setFocusPainted(false);
        bSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSairMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bSair))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(bSair)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    static int xx, yy;
    Border bordaCliqueTexto = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.decode("#04A58C"));
    Border bordaCliqueTextoFora = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("#9E9E9E"));


    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        tSenha.setEnabled(false);
        tCpf.setEnabled(false);
        if (tCpf.getText().equalsIgnoreCase("") && tSenha.getPassword().length == 0) {
            tCpf.setBorder(bordaCliqueTextoFora);
            tSenha.setBorder(bordaCliqueTextoFora);
            jLabel1.setForeground(Color.decode("#7A7A7A"));
            jLabel3.setForeground(Color.decode("#7A7A7A"));
            tCpf.setEnabled(true);
            tSenha.setEnabled(true);
        } else if (tCpf.getText().equalsIgnoreCase("")) {
            tCpf.setBorder(bordaCliqueTextoFora);
            tSenha.setBorder(bordaCliqueTexto);
            jLabel1.setForeground(Color.decode("#7A7A7A"));
            jLabel3.setForeground(Color.decode("#000000"));
            tCpf.setEnabled(true);
            tSenha.setEnabled(true);
        } else if (tSenha.getPassword().length == 0) {
            tCpf.setBorder(bordaCliqueTexto);
            tSenha.setBorder(bordaCliqueTextoFora);
            jLabel3.setForeground(Color.decode("#7A7A7A"));
            jLabel1.setForeground(Color.decode("#000000"));
            tCpf.setEnabled(true);
            tSenha.setEnabled(true);
        } else {
            tCpf.setBorder(bordaCliqueTexto);
            tSenha.setBorder(bordaCliqueTexto);
            jLabel1.setForeground(Color.decode("#000000"));
            jLabel3.setForeground(Color.decode("#000000"));
            tCpf.setEnabled(true);
            tSenha.setEnabled(true);
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void tCpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tCpfMouseClicked
        // TODO add your handling code here:
        tCpf.setTransferHandler(null);
        if (tCpf.getText().equalsIgnoreCase("")) {
            tCpf.setBorder(bordaCliqueTexto);
            jLabel1.setForeground(Color.decode("#000000"));
        }
        if (tSenha.getPassword().length == 0) {
            tSenha.setBorder(bordaCliqueTextoFora);
            jLabel3.setForeground(Color.decode("#7A7A7A"));
        } else {
            tSenha.setBorder(bordaCliqueTexto);
            jLabel3.setForeground(Color.decode("#000000"));
        }
    }//GEN-LAST:event_tCpfMouseClicked

    private void kGradientPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseClicked
        // TODO add your handling code here:
        tSenha.setEnabled(false);
        tCpf.setEnabled(false);
        if (tCpf.getText().equalsIgnoreCase("") && tSenha.getPassword().length == 0) {
            tCpf.setBorder(bordaCliqueTextoFora);
            tSenha.setBorder(bordaCliqueTextoFora);
            jLabel1.setForeground(Color.decode("#7A7A7A"));
            jLabel3.setForeground(Color.decode("#7A7A7A"));
            tCpf.setEnabled(true);
            tSenha.setEnabled(true);
        } else if (tCpf.getText().equalsIgnoreCase("")) {
            tCpf.setBorder(bordaCliqueTextoFora);
            tSenha.setBorder(bordaCliqueTexto);
            jLabel1.setForeground(Color.decode("#7A7A7A"));
            jLabel3.setForeground(Color.decode("#000000"));
            tCpf.setEnabled(true);
            tSenha.setEnabled(true);
        } else if (tSenha.getPassword().length == 0) {
            tCpf.setBorder(bordaCliqueTexto);
            tSenha.setBorder(bordaCliqueTextoFora);
            jLabel3.setForeground(Color.decode("#7A7A7A"));
            jLabel1.setForeground(Color.decode("#000000"));
            tCpf.setEnabled(true);
            tSenha.setEnabled(true);
        } else {
            tCpf.setBorder(bordaCliqueTexto);
            tSenha.setBorder(bordaCliqueTexto);
            jLabel1.setForeground(Color.decode("#000000"));
            jLabel3.setForeground(Color.decode("#000000"));
            tCpf.setEnabled(true);
            tSenha.setEnabled(true);
        }
    }//GEN-LAST:event_kGradientPanel1MouseClicked

    private void tSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tSenhaMouseClicked
        // TODO add your handling code here:
        tSenha.setTransferHandler(null);
        if (tSenha.getPassword().length == 0) {
            tSenha.setBorder(bordaCliqueTexto);
            jLabel3.setForeground(Color.decode("#000000"));
        }
        if (tCpf.getText().equalsIgnoreCase("")) {
            tCpf.setBorder(bordaCliqueTextoFora);
            jLabel1.setForeground(Color.decode("#7A7A7A"));
        } else {
            tCpf.setBorder(bordaCliqueTexto);
            jLabel1.setForeground(Color.decode("#000000"));
        }
    }//GEN-LAST:event_tSenhaMouseClicked

    private void tCpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCpfKeyReleased
        // TODO add your handling code here:    
        String numerosInseriosCpf = tCpf.getText();
        int quantiaNumerosDigitados = numerosInseriosCpf.length();
        if (quantiaNumerosDigitados > 14) {
            numerosInseriosCpf = numerosInseriosCpf.substring(0, numerosInseriosCpf.length() - 1);
            tCpf.setText(numerosInseriosCpf);
        }
    }//GEN-LAST:event_tCpfKeyReleased

    private void tCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCpfKeyPressed
        // TODO add your handling code here:
        String numerosInseriosCpf = tCpf.getText();
        int quantiaNumerosDigitados = numerosInseriosCpf.length();
        if (quantiaNumerosDigitados > 14) {
            numerosInseriosCpf = numerosInseriosCpf.substring(0, numerosInseriosCpf.length() - 1);
            tCpf.setText(numerosInseriosCpf);
        }
    }//GEN-LAST:event_tCpfKeyPressed

    private void tCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCpfKeyTyped
        // TODO add your handling code here:
        tCpf.setText(JMascara.GetJmascaraCpfCnpj(tCpf.getText()));
        String teclasAceitasCpf = ".-0123456789";
        if (!teclasAceitasCpf.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tCpfKeyTyped

    private void tSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSenhaKeyPressed
        // TODO add your handling code here:
        if (String.valueOf(tSenha.getPassword()).trim().length() > 32) {
            tSenha.setText(String.valueOf(tSenha.getPassword()).trim().substring(0, 32));
        }
    }//GEN-LAST:event_tSenhaKeyPressed

    private void labelMostrarSenhaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMostrarSenhaMousePressed
        // TODO add your handling code here:
        labelMostrarSenha.setVisible(false);
        labelOcultarSenha.setVisible(true);
        tSenha.setEchoChar((char) 0);
        tSenha.setFont(new java.awt.Font("Roboto Light", 0, 15));
    }//GEN-LAST:event_labelMostrarSenhaMousePressed

    private void labelOcultarSenhaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOcultarSenhaMousePressed
        // TODO add your handling code here:
        labelOcultarSenha.setVisible(false);
        labelMostrarSenha.setVisible(true);
        tSenha.setEchoChar('*');
        tSenha.setFont(new java.awt.Font("Tahoma", 0, 9));
    }//GEN-LAST:event_labelOcultarSenhaMousePressed

    private void labelMostrarSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMostrarSenhaMouseEntered
        // TODO add your handling code here:
        labelMostrarSenha.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labelMostrarSenhaMouseEntered

    private void labelOcultarSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOcultarSenhaMouseEntered
        // TODO add your handling code here:
        labelOcultarSenha.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labelOcultarSenhaMouseEntered

    private void tSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSenhaKeyReleased
        // TODO add your handling code here:
        if (String.valueOf(tSenha.getPassword()).trim().length() > 32) {
            tSenha.setText(String.valueOf(tSenha.getPassword()).trim().substring(0, 32));
        }
    }//GEN-LAST:event_tSenhaKeyReleased

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        AdministradorDAO aDAO = new AdministradorDAO();
        professorDAO pDAO = new professorDAO();
        String cpfMascara = JMascara.GetJmascaraLimpar(tCpf.getText());
        char[] converteSenha = tSenha.getPassword();
        String stringSenha = new String(converteSenha);
        boolean erro = false;
        if (cpfMascara.equals("")) {
            erro = true;
            JOptionPane.showMessageDialog(null, "cpf");
        } else if (stringSenha.equals("")) {
            erro = true;
            JOptionPane.showMessageDialog(null, "senha");
        } else if (radialProfessor.isSelected() == false & radialAdmin.isSelected() == false) {
            erro = true;
            JOptionPane.showMessageDialog(null, "botoes");
        }
        if (erro == true) {
            JOptionPane.showMessageDialog(null, "  Por favor!\n  Preencha todos os campos!");
            return;
        }
        if (radialProfessor.isSelected()) {
            if (pDAO.verificaLogin(cpfMascara, stringSenha)) {
                Professor p = pDAO.consultar(cpfMascara);
                new CadastrarNotas().setVisible(true);
                new Login_sucessoProfessor().setVisible(true);
                this.dispose();
            } else {
                new Login_falhaProfessor().setVisible(true);
            }
        } else if (radialAdmin.isSelected()) {
            if (aDAO.verificaLogin(cpfMascara, stringSenha)) {
                Admin a = aDAO.consultar(cpfMascara);
                new CadastrarAluno().setVisible(true);
                new Login_sucessoAdmin().setVisible(true);
                this.dispose();
            } else {
                new Login_falhaAdmin().setVisible(true);
            }
        }
    }//GEN-LAST:event_bLoginActionPerformed

    private void radialProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radialProfessorMouseClicked
        // TODO add your handling code here:
        radialProfessor.setForeground(Color.decode("#000000"));
        radialAdmin.setForeground(Color.decode("#7A7A7A"));
        radialAdmin.setSelected(false);
    }//GEN-LAST:event_radialProfessorMouseClicked

    private void radialAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radialAdminMouseClicked
        // TODO add your handling code here:
        radialAdmin.setForeground(Color.decode("#000000"));
        radialProfessor.setForeground(Color.decode("#7A7A7A"));
        radialProfessor.setSelected(false);
    }//GEN-LAST:event_radialAdminMouseClicked

    private void radialAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radialAdminMouseEntered
        // TODO add your handling code here:
        radialAdmin.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_radialAdminMouseEntered

    private void radialProfessorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radialProfessorMouseEntered
        // TODO add your handling code here:
        radialProfessor.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_radialProfessorMouseEntered

    private void bSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bSairMouseClicked

    private void bSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseEntered
        // TODO add your handling code here:
        bSair.setOpaque(true);
        bSair.setBackground(new Color(255, 96, 92));
        bSair.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_bSairMouseEntered

    private void bSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseExited
        // TODO add your handling code here:
        bSair.setOpaque(false);
    }//GEN-LAST:event_bSairMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton bLogin;
    private javax.swing.JButton bSair;
    private javax.swing.ButtonGroup buttonGroupLogin;
    private javax.swing.JLabel iconeLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lErroLogin;
    private javax.swing.JLabel labelMostrarSenha;
    private javax.swing.JLabel labelOcultarSenha;
    private javax.swing.JRadioButton radialAdmin;
    private javax.swing.JRadioButton radialProfessor;
    private javax.swing.JFormattedTextField tCpf;
    private javax.swing.JPasswordField tSenha;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
